language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  firefox: 46.0
before_script:
- npm install -g bower gulp-cli@1
- bower install
- gulp lint
- gulp switch
script:
- xvfb-run wct -l firefox --verbose
