language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  firefox: latest
before_script:
- npm install -g bower gulp-cli@1
- bower install
- gulp lint
- gulp switch
script:
- xvfb-run -s '-screen 0 1024x768x24 +extension RANDR -ac' wct -l firefox --verbose
