language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  firefox: latest-beta
before_script:
- npm install -g bower gulp-cli@1
- bower install
- gulp lint
- gulp switch
script:
- RUST_LOG=debug xvfb-run node_modules/.bin/wct -l firefox --verbose
